### ISSUE TITLE
Still empty repo

### ISSUE THREAD

**Issue by mfentross** [ImmobilienScout24/restapi-java-sdk#1]
When will there finally be something to use?

**Comment by killaqueen** [comment]
Hi,

thanks for your interest in the IS24 java-sdk and sorry for the late response. I was absent for a wihle. 

We are currently working on finalizing the API for the SDK and are planning to release it as soon as possible.

Cheers,

Martin

**Comment by mfentross** [comment]
Hi Martin,

thanks for your reply. What should we expect how long that finalizing will take? Days? Weeks?

I am asking because we need to build in an IS24 function in a Scala project better yesterday than today.

M

**Comment by killaqueen** [comment]
Hi,

unfortunately I am quite busy with other things at the moment. I plan to finish the first version in 19th or 20th calender week. It might be earlier but I cannot promise it. Sorry.

Cheers,

Martin

**Comment by torsten-sauer** [comment]
Hi,

week 23 started and no release :-(
We're waiting for the SDK to - even a beta version would help so we can start developing...

Cheers,
Torsten

**Comment by killaqueen** [comment]
Torsten,

I committed the inital version. Please do not consider the APi as stable yet as it is only a beta version. But it compiles with "mvn clean install" to an usable jar and you can also use "mvn eclipse:eclispe" to prepare the project for Eclipse, if you are using it. Currently to build is bound to Java 1.7 but I think we will make it compatible to Java 1.6 if someone requests it. 

If you face any trouble, please let me know.

Cheers,

Martin

**Comment by torsten-sauer** [comment]
Hey Martin,

thanks for the code! I will try it as soon as possible and let you know if it works ;-)

Cheers,
Torsten
